ALTER TABLE books
  ADD COLUMN IF NOT EXISTS image_storage_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pdf_storage_name VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS pdf_original_name VARCHAR(255) DEFAULT NULL;
